name = "zotero"
main = "src/worker.js"
compatibility_date = "2025-01-15"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "zotero.1000jeff.uk/*"
zone_name = "1000jeff.uk"

[vars]
AUTH_USERNAME = "nl"
